SELECT 
    p.ID, 
    TIMESTAMPDIFF(MONTH, p.START_DATE, p.FINISH_DATE) as MONTH_COUNT
FROM 
    project p
WHERE 
    TIMESTAMPDIFF(MONTH, p.START_DATE, p.FINISH_DATE) = (
        SELECT MAX(TIMESTAMPDIFF(MONTH, START_DATE, FINISH_DATE)) 
        FROM project
    );